### ISSUE TITLE
Erratic behavior on BluetoothDeviceEvent

### ISSUE THREAD

**Issue by jcyu0208** [kontaktio/kontakt-android-sdk#99] opened 2016-03-20 16:33 UTC
I'm currently working on a PoC and have this configuration for my scan context

```
protected List<EventType> getEventTypes() {
        return Arrays.asList(
                EventType.SPACE_ENTERED,
                EventType.DEVICE_DISCOVERED,
                EventType.DEVICES_UPDATE, //Returns the namespace and 1 beacon
                EventType.DEVICE_LOST,
                EventType.SPACE_ABANDONED
        );
    }
EddystoneScanContext eddystoneScanContext = new EddystoneScanContext.Builder()
                .setEddystoneNamespaces(/* namespaces */)
                .setEventTypes(getEventTypes())
                .setDistanceSort(DistanceSort.ASC)
                .setRssiCalculator(RssiCalculators.newLimitedMeanRssiCalculator(3))
                .build();

return new ScanContext.Builder()
                .setEddystoneScanContext(eddystoneScanContext)
                .setScanMode(ProximityManager.SCAN_MODE_BALANCED)
                .setScanPeriod(TimeUnit.SECONDS.toMillis(5), TimeUnit.SECONDS.toMillis(0)))
                .setForceScanConfiguration(ForceScanConfiguration.MINIMAL)
                .setActivityCheckConfiguration(new ActivityCheckConfiguration(TimeUnit.SECONDS.toMillis(10), TimeUnit.SECONDS.toMillis(5)))
                .build();
```

I am getting two completely different behavior on 2 android devices.

1st Device:
Gets updated regularly.
Does not receive the DEVICE_LOST event

2nd Device:
Updates usually take around 5 seconds or more
Devices are randomly set to lost, even when they're not supposed to be lost. 
1. Is there any problem with my Scan Context configuration?
2. Is this expected from Android devices? If the event types are unreliable on Android devices, it won't be a good idea if we would rely on it for business logic.

EDIT:
I have a 1 minute video showing the behavior on 3 different devices. Each device shows a different output for the events despite running the same program. Let me know how I can send this video to you guys.

**Comment by michaldrabik** [comment] 2016-03-20 18:01
@jcyu0208 Unfortunately Android is known for its BLE problems, especially on lower-end devices. Your ScanContext looks ok (you don't need to specify EventTypes explicitly if you wish to listen for all of them). 

Be aware that DEVICE_LOST event will be posted after the time specified in `.setActivityCheckConfiguration(new ActivityCheckConfiguration(TimeUnit.SECONDS.toMillis(10), TimeUnit.SECONDS.toMillis(5)))`, so lets say you take out battery from you Beacon - in this case the Beacon will be reported "LOST" after 10 seconds.

Feel free to upload this video to YouTube and share link here.

**Comment by jcyu0208** [comment] 2016-03-21 02:30
`Be aware that DEVICE_LOST event will be posted after the time specified in .setActivityCheckConfiguration(new ActivityCheckConfiguration(TimeUnit.SECONDS.toMillis(10), TimeUnit.SECONDS.toMillis(5))), so lets say you take out battery from you Beacon - in this case the Beacon will be reported "LOST" after 10 seconds.`

What's happening is that it stays there indefinitely and is always part of the DEVICE_UPDATED event.

**Comment by michaldrabik** [comment] 2016-03-22 07:18
@jcyu0208 I will reproduce your code and try it on my devices. Will be getting back to you.

**Comment by cboisen** [comment] 2016-05-31 14:38
I too is getting update event indefinitely (at least it seems so, waited for 2+ minutes multiple times) when I disconnect my usb beacon. The device lost is never called.

Tested on Oneplus 2 & OnePlus 1, with SDK version 2.1.\* and 3.0.0.

**Comment by michaldrabik** [comment] 2016-05-31 15:27
@hauthorn What is OS version of your devices? Also could you paste some code that you are using for scanning (preferably from 3.0.0 SDK)

**Comment by hauthorn** [comment] 2016-06-01 07:08
@michaldrabik My Oneplus 2 is on Android 5.1.1. The Oneplus 1 is on Android 6-something. Trying on a Sony Experia running 4.4.4 (API 19) yields similar results - The update callback still returns the usb beacon long after it has been unplugged.

My code using 3.0.0: https://gist.github.com/hauthorn/d22a83dadb72ba15e3c4906ddfc39632

I had similar configuration when using the 2.1.2 version.

**Comment by cboisen** [comment] 2016-06-01 07:35
@michaldrabik Actually I am having trouble repeating the issue on 3.0.0. Maybe the update did fix the issue. I will investigate further.

My code at the moment (using sdk 3.0.0): https://gist.github.com/hauthorn/d22a83dadb72ba15e3c4906ddfc39632

I had similar config using 2.1.2.

**Comment by cboisen** [comment] 2016-06-01 07:43
Tried using the above code on the following phones:
- Oneplus One (Android 6.0.1). It does eventually call "lost" for the device. Though it took 30+ seconds
- Oneplus Two (Android 5.1.1). It never receives the "lost" call for the device. It just keeps getting updates where the unplugged beacon is in the list with last known distance/rssi
- Sony Experia (Android 4.4.2). It does drop the beacon, and does it sooner than the Oneplus One.

Update: This is somewhat periodic. Sometimes the devices (oneplus 1 & 2) keep getting updates long after the usb-beacon is unplugged. Waited for 2+ minutes.

**Comment by michaldrabik** [comment] 2016-06-01 15:37
@hauthorn Could you change ScanPeriod to ScanPeriod.RANGING and tell me if the problem remains?

Also you can move configuration and listeners settings out of connect block for prettier code:
https://gist.github.com/michaldrabik/787c832d1d1a3031465820090ab6cfe5

**Comment by cboisen** [comment] 2016-06-01 17:47
@michaldrabik This seems to improve the situation. After 2 tests both OnePlus' "remove" the beacon after 5-10 seconds (worst case was 12 seconds) after unplugging the device.

Can you elaborate on the inner working of the ActivityCheck? I would love to use settings that are less power-demanding while still using the ActivityCheck. Alternatively, I would like to disable the local cache entirely, and rely on my own implementation.

PS.
I have the config separate in production code. The test example i'm using and posted was simply to get everything in the same place to make it easier for you guys to read :+1:

**Comment by michaldrabik** [comment] 2016-06-02 06:24
@hauthorn As stated in javadocs: 
ActivityCheck configuration describes the time boundary after which the beacon device is interpreted as absent and than is removed from internal cache. The configuration consists of 2 parameters - removal inactivityTimeout and checkPeriod. The former describes time threshold after which beacon device is interpreted as inactive and should be removed. The latter specifies period of search of inactive beacons.

As of right now, the minimal possible values are 5000, 5000 millis (ActivityCheckConfiguration.MINIMAL). So whenever monitoring cycle starts, activity check will be performed every 5 seconds and if the scanner hasn't received beacon's signal for 5 seconds it will assume it as inactive. The activity check stops when monitoring cycle ends. What I think is happening here is that when monitoring cycle is the same as activitycheck its going crazy (it doesn't get a chance to check for inactive beacons because monitoring cycle ends at the same time). We will investigate further.

Within next update I will drop the minimal possible ActivityCheck values to 1 seconds, 1 second. So the users will have more freedom when setting it. The BETA version with stated changes is already available on the beta channel so feel free to give it a try. To do this change version to 3.0.1 and add our beta repository to you gradle file. Like this:

```
repositories {
  maven {
    url  "http://dl.bintray.com/kontaktio/maven"
  }
}

dependencies {
  ...
  compile 'com.kontaktio:sdk:3.0.1'
}
```

Try using ActivityCheckPeriod like (3000, 1000) with ScanPeriod.RANGING and see if the results are better. You could then experiment with different scan periods.

Regards.

**Comment by cboisen** [comment] 2016-06-02 07:18
@michaldrabik I guess I didn't realize the relationship between the monitoring cycle and the activity check. I thought the ActivityCheck ran somewhat independent of the monitoring cycle. In my previous setup I thought the ActivityCheck would run after the monitoring-period had ended, and work just fine.

I've changed the config in our apps to reflect the change. This didn't really affect real-life performance that much, since we don't remove batteries og unplug beacons in the production environment.
I will play with the beta sometime after our next release-cycle.

Thank you for your time!

**Comment by michaldrabik** [comment] 2016-06-02 07:37
Closing. Feel free to reopen if necessary.

**Closed as completed by michaldrabik** 2016-06-02 07:37 UTC
