### ISSUE TITLE
Scan failed - application registration failed

### ISSUE THREAD

**Issue by DestaSoftware** [kontaktio/kontakt-android-sdk#181] opened 2018-02-23 09:16 UTC
Hello!
Starting to receive callback of onScanError(...) with such (subj) message. After phone's cold restarting all working good during short time (about 10-20 or 30 minutes). After this onScanError come back. 
restartScaning() not help, stop/start scaning not help.
Phone - Xiaomi Redme 4x. SDK - 4.0.0.
Please, help. What should I do? What that message (subj) mean?

**Comment by verma171** [comment] 2018-02-28 14:09
I am also getting the same issue on Oneplus 5

**Comment by sbobowiec** [comment] 2018-07-25 20:50
Hello,
What is the exact string message of error? Could you also paste you `ProximityManager` configuration code here?
FYI current version of our SDK is now 4.0.2. Please try to use it and let me know if problem still exists.

**Comment by ImadLakehal** [comment] 2018-09-27 15:28
@sbobowiec or any person who can help, I would like to let my C# App to communicate with my kontakt.io beacons, please can you give me indications or examples about how should be the project's classes architecture in order to scan the beacons in the area. Thanks in advance.

**Comment by cboisen** [comment] 2019-02-22 13:49
I have the same error on a HUAWEI WAS-LX1 (P10 lite i think it's called). The onScanError callback is called, and the exception message is "Scan failed - application registration failed". It seems to happen periodically (it had been turned for quite a while before this became an issue).

**Comment by ghost** [comment] 2019-09-04 15:46
I suppose if you restart the phone it will work again.

Could it be a close issue:

https://stackoverflow.com/questions/25330938/android-bluetoothgatt-status-133-register-callback
https://issuetracker.google.com/issues/36993728

**Comment by robertbielas** [comment] 2021-11-08 13:54
Registration failure means that the limit of BT clients has been reached on your phone.

Either you had too many BT accessories connected to your phone, or the crashes of the apps on your phone caused some leaks that prevented the already registered clients from unregistering.

Restarting the phone or simply turning your BT off / on will do the trick, but is only a temporary workaround with the root cause still remaining to wreak havoc.

Closing the issue - 3 years passed since the ticket was opened, there is no way to gather the logs necessary to debug it. Feel free to reopen if the situation recreates on sdk 5.0.xx (which is the series of the currently supported sdks).

**Closed as completed by robertbielas** 2021-11-08 13:54 UTC
